server:
  port: 8088
spring:
  application:
    name: user-provider
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      rate: 1
eureka:
  client:
    service-url:
      defaultZone: http://euk1:8082/eureka,http://euk1:8083/eureka